
[font]
  size = 14.0

[font.normal]
  family = "JetBrainsMono NF"

#[terminal.shell]
 # args = ["new-session", "-A", "-D", "-s", "main"]
  #program = "/usr/bin/tmux"

[window]
  decorations = "none"
  startup_mode = "Maximized"

[window.padding]
  x = 7
  y = 0

[general]
live_config_reload = true
import = ["/home/dave/.config/alacritty/themes/gruvbox.toml"]

[terminal]
